FROM node:20-alpine

WORKDIR /usr/src/vj-store

COPY ./dist/ /usr/src/vj-store/dist/
COPY ./package.json /usr/src/vj-store/package.json
COPY ./package-lock.json /usr/src/vj-store/package-lock.json

RUN npm install

EXPOSE 5000
EXPOSE 9222

CMD ["npm", "run", "debug"]
