FROM node:18-alpine

WORKDIR /usr/src/vj-store

COPY ./package.json /usr/src/vj-store/package.json
COPY ./package-lock.json /usr/src/vj-store/package-lock.json

RUN npm install

CMD ["npm", "run", "test"]
