FROM node:18-alpine

WORKDIR /usr/src/vj-store

RUN addgroup -S appgroup && adduser -S appuser -G appgroup
RUN chown -R appuser:appgroup /usr/src/vj-store
USER appuser

COPY --chown=appuser:appgroup ./dist/ /usr/src/vj-store/dist/
COPY --chown=appuser:appgroup ./package.json /usr/src/vj-store/package.json
COPY --chown=appuser:appgroup ./package-lock.json /usr/src/vj-store/package-lock.json

RUN find /usr/src/vj-store -type f -executable -exec chmod go-w {} +

RUN npm install

EXPOSE 5000
EXPOSE 9222

CMD ["npm", "run", "debug"]
