version: '3'

services:
  mongodb:
    container_name: vj-store-mongodb
    image: mongo:7
    restart: always
    volumes:
      - ./data:/data/db
    ports:
      - 27017:27017
  api:
    container_name: vj-store
    build:
      context: .
      dockerfile: Dockerfile.dev
    environment:
      - MONGO_URL=mongodb://vj-store-mongodb:27017/vj-store
      - PORT=5000
    volumes:
      - ./dist:/usr/src/vj-store/dist/
      - ./package.json:/usr/src/vj-store/package.json
    ports:
      - 5000:5000
      - 9222:9222
    links:
      - mongodb
