FROM node:18-alpine

WORKDIR /usr/src/vj-store

RUN apk --no-cache add --virtual builds-deps build-base python3

RUN addgroup -S appgroup && adduser -S appuser -G appgroup

COPY --chown=root:root --chmod=644 ./dist/ /usr/src/vj-store/dist/
COPY --chown=root:root --chmod=644 ./package.json /usr/src/vj-store/package.json
COPY --chown=root:root --chmod=644 ./package-lock.json /usr/src/vj-store/package-lock.json

RUN chown -R appuser:appgroup /usr/src/vj-store

USER appuser

RUN npm install --ignore-scripts
RUN npm rebuild bcrypt --build-from-source

EXPOSE 5000
EXPOSE 9222

CMD ["npm", "run", "debug"]
