version: 2.1

jobs:
  test:
    docker:
      - image: docker:stable

    working_directory: ~/app

    steps:
      - checkout

      - run:
          name: Build Docker image
          command: docker build -t vj-store-test -f Dockerfile.test .

      - run:
          name: Run Tests in Docker
          command: docker run vj-store-test

workflows:
  build_and_test:
    jobs:
      - test
  