version: 2.1

jobs:
  build:
    docker:
      - image: node:18

    working_directory: ~/app

    steps:
      - checkout

      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}

      - run:
          name: Install dependencies
          command: |
            npm install
            apt-get update
            apt-get install gdebi-core -y
            wget http://ftp.us.debian.org/debian/pool/main/o/openssl/libssl1.1_1.1.1n-0+deb11u4_amd64.deb
            gdebi --non-interactive libssl1.1_1.1.1n-0+deb11u4_amd64.deb

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      - run:
          name: Run Tests
          command: npm test
