name: Test Coverage

on: [push]

jobs:
  build:
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: |
          npx jest --coverage --coverageReporters json-summary

      - uses: ArtiomTr/jest-coverage-report-action@v2
